package org.firstinspires.ftc.teamcode.opmodes;

import com.bylazar.configurables.annotations.Configurable;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;

import org.firstinspires.ftc.teamcode.Robot;
import org.firstinspires.ftc.teamcode.commands.IntakeCommands.IntakeCommands;
import org.firstinspires.ftc.teamcode.commands.LauncherCommands.LauncherCommands;
import org.firstinspires.ftc.teamcode.pedroPathing.Constants;
import org.firstinspires.ftc.teamcode.subsystems.DriveSubsystem;
import org.firstinspires.ftc.teamcode.subsystems.IntakeSubsystem;
import org.firstinspires.ftc.teamcode.subsystems.LauncherSubsystem;
import org.firstinspires.ftc.teamcode.subsystems.LightingSubsystem;
import org.firstinspires.ftc.teamcode.util.Alliance;
import org.firstinspires.ftc.teamcode.util.AllianceSelector;
import org.firstinspires.ftc.teamcode.util.AutoField;
import org.firstinspires.ftc.teamcode.util.AutoRoutineBuilder;
import org.firstinspires.ftc.teamcode.util.LauncherMode;
import org.firstinspires.ftc.teamcode.util.LauncherRange;
import org.firstinspires.ftc.teamcode.util.RobotState;

import dev.nextftc.bindings.BindingManager;
import dev.nextftc.core.commands.Command;
import dev.nextftc.core.commands.CommandManager;
import dev.nextftc.core.commands.delays.Delay;
import dev.nextftc.core.commands.groups.SequentialGroup;
import dev.nextftc.core.commands.utility.InstantCommand;
import dev.nextftc.core.components.BindingsComponent;
import dev.nextftc.core.components.SubsystemComponent;
import dev.nextftc.extensions.pedro.PedroComponent;
import dev.nextftc.ftc.GamepadEx;
import dev.nextftc.ftc.NextFTCOpMode;
import dev.nextftc.ftc.components.BulkReadComponent;

/**
 * PROOF-OF-CONCEPT: Command-based autonomous generated from .pp file
 *
 * This OpMode demonstrates the AutoRoutineBuilder system, which allows you to:
 * 1. Load paths from .pp files (created with Pedro Pathing GUI)
 * 2. Add game-specific actions (intake, launcher, etc.)
 * 3. Control speed, heading interpolation, and timing per segment
 *
 * Key features demonstrated:
 * - Loading trajectory.pp file
 * - Granular per-segment power control ("slow down the 3rd path")
 * - Heading interpolation control (linear vs tangential)
 * - Actions before/during/after each segment
 * - Alliance-aware path mirroring
 */
@Autonomous(name = "DEMO: Generated Auto from .pp", group = "Generated")
@Configurable
public class DecodeAutoGeneratedExample extends NextFTCOpMode {

    private static final Alliance DEFAULT_ALLIANCE = Alliance.BLUE;

    @Configurable
    public static class AutoConfig {
        /** Default power for path following */
        public double defaultPower = 0.8;

        /** Power for slower segments */
        public double slowPower = 0.5;

        /** Intake delay before reversing (seconds) */
        public double intakeDelaySeconds = 0.1;

        /** Starting launcher mode */
        public LauncherMode startingLauncherMode = LauncherMode.THROUGHPUT;

        /** Which .pp file to use (without .pp extension) */
        public String ppFileName = "trajectory.pp";
    }

    public static AutoConfig config = new AutoConfig();

    private Robot robot;
    private AllianceSelector allianceSelector;
    private Alliance activeAlliance = Alliance.BLUE;
    private IntakeCommands intakeCommands;
    private LauncherCommands launcherCommands;
    private LightingSubsystem.InitController lightingInitController;

    {
        addComponents(
            BulkReadComponent.INSTANCE,
            new PedroComponent(Constants::createFollower),
            BindingsComponent.INSTANCE,
            CommandManager.INSTANCE
        );
    }

    @Override
    public void onInit() {
        BindingManager.reset();
        robot = new Robot(hardwareMap);

        robot.attachPedroFollower();
        robot.drive.setRobotCentric(DriveSubsystem.robotCentricConfig);
        robot.telemetry.startSession();
        robot.initializeForAuto();

        // Initialize command factories
        intakeCommands = new IntakeCommands(robot.intake);
        launcherCommands = new LauncherCommands(robot.launcher, robot.intake);

        // Alliance selection
        GamepadEx driverPad = new GamepadEx(() -> gamepad1);
        allianceSelector = new AllianceSelector(driverPad, Alliance.UNKNOWN);
        activeAlliance = allianceSelector.getSelectedAlliance();
        robot.setAlliance(activeAlliance);
        allianceSelector.applySelection(robot, robot.lighting);

        addComponents(
            new SubsystemComponent(robot.drive),
            new SubsystemComponent(robot.launcher),
            new SubsystemComponent(robot.intake),
            new SubsystemComponent(robot.lighting),
            new SubsystemComponent(robot.vision)
        );
    }

    @Override
    public void onWaitForStart() {
        BindingManager.update();
        robot.intake.periodic();
        robot.vision.periodic();

        // Update alliance from vision
        allianceSelector.updateFromVision(robot.vision);
        allianceSelector.applySelection(robot, robot.lighting);

        Alliance selectedAlliance = allianceSelector.getSelectedAlliance();
        if (selectedAlliance != activeAlliance) {
            activeAlliance = selectedAlliance;
            robot.setAlliance(activeAlliance);
        }

        telemetry.clear();
        telemetry.addData("Alliance", activeAlliance.displayName());
        telemetry.addData("PP File", config.ppFileName);
        telemetry.addLine();
        telemetry.addLine("This is a DEMO of .pp file auto generation");
        telemetry.addLine("Edit buildAutonomousRoutine() to customize");
        telemetry.addLine();
        telemetry.addData("Artifacts", "%d detected", robot.intake.getArtifactCount());
        telemetry.addLine("Press START when ready");
        telemetry.update();
    }

    @Override
    public void onStartButtonPressed() {
        BindingManager.reset();
        allianceSelector.lockSelection();

        // Initialize launcher mode from config
        RobotState.setLauncherMode(config.startingLauncherMode);
        RobotState.resetMotifTail();

        robot.launcher.setSpinMode(LauncherSubsystem.SpinMode.FULL);
        robot.intake.forwardRoller();
        robot.intake.setGateAllowArtifacts();

        // Build and schedule the autonomous routine FROM .PP FILE
        Command autoRoutine = buildAutonomousRoutine();
        CommandManager.INSTANCE.scheduleCommand(autoRoutine);
    }

    @Override
    public void onUpdate() {
        publishTelemetry();
    }

    @Override
    public void onStop() {
        allianceSelector.unlockSelection();
        BindingManager.reset();
        robot.launcher.abort();
        robot.drive.stop();
        robot.vision.stop();

        // Save final pose for TeleOp transition
        RobotState.setHandoffPose(robot.drive.getFollower().getPose());
    }

    /**
     * BUILD AUTONOMOUS ROUTINE FROM .PP FILE
     *
     * This demonstrates the granular control you requested:
     * - Each segment can have different power
     * - Each segment can have different heading interpolation
     * - Actions can be added before/during/after any segment
     */
    private Command buildAutonomousRoutine() {
        // trajectory.pp has 4 path segments:
        // Path 1: (56, 8) -> (56.27, 19.81) - Initial movement
        // Path 2: (56.27, 19.81) -> (23.77, 23.77) - Drive to pickup
        // Path 3: (23.77, 23.77) -> (23.51, 39.63) - Collect samples
        // Path 4: (23.51, 39.63) -> (56.27, 19.55) - Return to score

        try {
            return AutoRoutineBuilder
                .fromPpFile(config.ppFileName, robot, hardwareMap, activeAlliance)

                // SEGMENT 1: Drive to launch position
                .followNext()
                    .withPower(config.defaultPower)           // Normal speed
                    .withLinearHeading()                      // Linear heading interpolation
                    .during(spinUpLauncher())                 // Spin up while driving
                .andThen()

                .then(scoreSequence())  // Score preload

                // SEGMENT 2: Drive to pickup location
                .followNext()
                    .withPower(config.defaultPower)
                    .withTangentialHeading()                  // USE TANGENTIAL (as requested!)
                    .during(prepareIntake())                  // Prepare intake while driving
                .andThen()

                // SEGMENT 3: Collect samples (SLOWER as requested!)
                .followNext()
                    .withPower(config.slowPower)              // SLOW DOWN THE 3RD PATH!
                    .withHeadingInterpolation(0.7)           // Custom interpolation (0.0-1.0)
                    .during(new InstantCommand(() ->
                        robot.intake.setMode(IntakeSubsystem.IntakeMode.ACTIVE_FORWARD)))
                .andThen()

                .delay(config.intakeDelaySeconds)  // Wait for intake

                // SEGMENT 4: Return to score
                .followNext()
                    .withPower(config.defaultPower)           // Back to normal speed
                    .withLinearHeading()
                    .during(spinUpLauncher())                 // Spin up while returning
                .andThen()

                .then(scoreSequence())  // Score collected samples

                .build();

        } catch (Exception e) {
            telemetry.addData("ERROR", "Failed to load .pp file: " + e.getMessage());
            telemetry.update();
            return new Delay(0.01);
        }
    }

    /**
     * Example: You can also follow segments by name instead of order
     */
    private Command buildAlternativeRoutine() {
        return AutoRoutineBuilder
            .fromPpFile(config.ppFileName, robot, hardwareMap, activeAlliance)

            .followSegment("Path 1")
                .withPower(0.9)
                .during(spinUpLauncher())
            .andThen()

            .followSegment("Path 2")
                .withPower(0.8)
            .andThen()

            // Skip Path 3 entirely

            .followSegment("Path 4")
                .withPower(0.5)
            .andThen()

            .build();
    }

    // ============ HELPER METHODS (same as existing autos) ============

    private Command prepareIntake() {
        return new InstantCommand(() -> robot.intake.startForward());
    }

    private Command spinUpLauncher() {
        // Use your existing launcher commands
        return launcherCommands.spinUpForPosition(AutoField.FieldPoint.LAUNCH_FAR);
    }

    private Command scoreSequence() {
        return new SequentialGroup(
            launcherCommands.launchAllAtRangePreset(LauncherRange.LONG, false)
        );
    }

    private void publishTelemetry() {
        robot.telemetry.publishLoopTelemetry(
            robot.drive,
            robot.launcher,
            robot.intake,
            robot.vision,
            robot.lighting,
            null,
            gamepad1,
            gamepad2,
            RobotState.getAlliance(),
            getRuntime(),
            Math.max(0.0, 150.0 - getRuntime()),
            telemetry,
            "Generated Auto",
            true,
            null,
            0,
            0
        );
    }
}
